Rem  SQL Access Advisor: Version 21.0.0.0.0 - Production
Rem  
Rem  Username:        HOPITAL
Rem  Task:            TASK_GESTION_CABINET_MEDICAL
Rem  Execution date:  26/10/2024 19:42
Rem  

/* RETAIN INDEX "HOPITAL"."PK_CONSULTATION" */

/* RETAIN INDEX "HOPITAL"."PK_PATIENT" */

/* RETAIN INDEX "HOPITAL"."PK_FACTURE" */

CREATE INDEX "HOPITAL"."EXAMEN_IDX$$_00130000"
    ON "HOPITAL"."EXAMEN"
    ("DETAILS_EXAMEN")
    COMPUTE STATISTICS;

